version: '3.8'

services:
  franquicias-app:
    build: .
    image: franquicias-app
    container_name: franquicias-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://franquiciasAdmin:adminadmin@cluster0.scxvxmk.mongodb.net/franquicias-db?retryWrites=true&w=majority&appName=Cluster0